// FDX v6 constants and enums

const ACCOUNT_CATEGORIES = {
  DEPOSIT: 'DEPOSIT_ACCOUNT',
  LOAN: 'LOAN_ACCOUNT',
  LOC: 'LOC_ACCOUNT',
};

const ACCOUNT_TYPES = {
  CHECKING: 'CHECKING',
  SAVINGS: 'SAVINGS',
  MORTGAGE: 'MORTGAGE',
  LINE_OF_CREDIT: 'LINE_OF_CREDIT',
  CREDIT_CARD: 'CREDIT_CARD',
};

const ACCOUNT_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  PENDING: 'PENDING',
  FROZEN: 'FROZEN',
};

const TRANSACTION_TYPES = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
};

const TRANSACTION_STATUS = {
  POSTED: 'POSTED',
  PENDING: 'PENDING',
  MEMO: 'MEMO',
};

const DATA_CLUSTERS = {
  ACCOUNT_BASIC: 'ACCOUNT_BASIC',
  ACCOUNT_DETAILED: 'ACCOUNT_DETAILED',
  TRANSACTIONS: 'TRANSACTIONS',
  STATEMENTS: 'STATEMENTS',
  BALANCES: 'BALANCES',
  PAYMENT_SUPPORT: 'PAYMENT_SUPPORT',
};

const OAUTH_SCOPES = Object.values(DATA_CLUSTERS);

const TOKEN_TTL = {
  AUTH_CODE_MS: 10 * 60 * 1000,          // 10 minutes
  ACCESS_TOKEN_MS: 30 * 60 * 1000,       // 30 minutes
  REFRESH_TOKEN_MS: 90 * 24 * 60 * 60 * 1000, // 90 days
  CONSENT_MS: 365 * 24 * 60 * 60 * 1000, // 12 months
};

const FDX_ERROR_CODES = {
  INTERNAL_ERROR: 500,
  CUSTOMER_NOT_FOUND: 601,
  CUSTOMER_NOT_AUTHORIZED: 602,
  ACCOUNT_NOT_FOUND: 701,
  INVALID_START_DATE: 704,
  INVALID_END_DATE: 705,
  TOO_MANY_REQUESTS: 429,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
};

const PAGINATION_DEFAULTS = {
  LIMIT: 100,
  MAX_LIMIT: 500,
};

const CURRENCY = 'CAD';

module.exports = {
  ACCOUNT_CATEGORIES,
  ACCOUNT_TYPES,
  ACCOUNT_STATUS,
  TRANSACTION_TYPES,
  TRANSACTION_STATUS,
  DATA_CLUSTERS,
  OAUTH_SCOPES,
  TOKEN_TTL,
  FDX_ERROR_CODES,
  PAGINATION_DEFAULTS,
  CURRENCY,
};
